### ISSUE TITLE
[Fix] setSceneCoverFromFile fails to run with SSL and self-signed certificate

### ISSUE THREAD

**Issue by Ksrx01** [stashapp/CommunityScripts#110]
I'm running Stash over SSL with a self-signed certificate, tried to use this plugin, which failed, as it obviously was unable to verify the certificate. So I change **Line:64** in `stash_interface.py` from:

> `response = requests.post(self.url, json=json, headers=self.headers, cookies=self.cookies)`

to

> `response = requests.post(self.url, json=json, headers=self.headers, cookies=self.cookies, verify=False)`

While far from being optimal, it might be worth considering to apply this change to the repo.
I guess, considering the context in which this is being used, it shouldn't be a a major security threat.

**Comment by bnkai** [comment]
It is probably `safe` enough to override the verify by default (considering the use case).
Thanks for the report will make a PR when possible

**Comment by scruffynerf** [comment]
Solved by #188
