### ISSUE TITLE
[renamerOnUpdate] Path is too long

### ISSUE THREAD

**Issue by AldanaFan** [stashapp/CommunityScripts#119]
If I understood it correctly from the config file, the tool should be able to adjust the filename in case the path violates the windows maximum path length constraint. However, this doesn't work for me.

I would like to have my files named  `<studio> - <title> - <performes sorted by gender> (<Date>)`

In case the path would be too long, first the performers shall be removed, then studio and finally the date. I have attached my config file, maxbe I have configured something wrong, but it doesn't work for me.

If you check the logs the following error is thrown:
022-12-10 12:28:50Error   [Plugin / renamerOnUpdate] The path is too long (431 > 240)

For testing purposes I used scene SZ2788 from Legal P#rn#

Stash Version is v0.17.2
renamerOnUpdate Version is 2.4.0

[config.zip](https://github.com/stashapp/CommunityScripts/files/10199952/config.zip)

**Comment by bnkai** [comment]
Related PR is merged. Closing this as fixed/completed
