### ISSUE TITLE
[DateParser] ImportError if using latest stashapi-tools (0.2.17)

### ISSUE THREAD

**Issue by imagineimaginingthings** [stashapp/CommunityScripts#121]
As of me writing this, the most recent update to stashapi-tools (0.2.17) has effectively broken this plugin, due to the removal of `stashapp_gql_fragments.py` (see [this commit](https://github.com/stg-annon/stashapi/commit/5cdbc013ef0ea55c5fa0565c414a9cbd6a0ec9c3)).

So now we get:
```
[Plugin / Date Parser]     ImportError: cannot import name 'stashapp_gql_fragments' from 'stashapi.stashapp' (C:\Python311\Lib\site-packages\stashapi\stashapp.py)
[Plugin / Date Parser]     from stashapi.stashapp import StashInterface, stashapp_gql_fragments
```

Sorry I don't speak Python to know exactly what needs to be done, but presumably it just needs a little refactoring to account for what's been moved.

I've downgraded to 0.2.16 in the meantime so I can still use this (`pip install -Iv stashapp-tools==0.2.16` for anyone else who needs to) but it would be nice to be using the latest version of things.

**Comment by HijackHornet** [comment]
Thanks for this great analysis of the issue. I bumped the version but i'm facing another issue. When i solve it i'll make an update

**Comment by bnkai** [comment]
Issue fixed with latest version of the plugin. Closing
