### ISSUE TITLE
[renamerOnUpdate] replace_text function: need to assign tmp to text at the end of each iteration

### ISSUE THREAD

**Issue by BlokeCDP** [stashapp/CommunityScripts#132]
At the end of each iteration in the for old, new loop in renamerOnUpdate.py we need to assign tmp to text
i.e. 
text = tmp 

If we don't do this, and we have multiple replacement words, we end up only applying the last replacement. This is because we call re.sub passing in the **text** variable:
tmp = re.sub(fr'([\s_-])({old})([\s_-])', f'\\1{new[0]}\\3', **text**)

e.g. 
Dp -> DP
Bbc -> BBC

text passed into replace_text function: TestFile Dp Bbc

First iteration: **text** passed to re.sub 
Replaces Dp with DP
tmp = TestFile DP Bbc

Next iteration to handle Bbc:, **text** passed to re.sub - "TestFile Dp Bbc"
Replaces Bbc with BBC
tmp = TestFile Dp BBC

We've "lost" the first iteration Dp replacement.
text = tmp fixes that.

Either that, or assign tmp = text in the first line of the function and pass tmp to re.sub - that way you can have what you passed in and what it was changed to (i.e before and after).

I am a complete novice on github so am not confident of resolving this myself, so I hope this helps explain the issue and the relatively simple fix.

Cheers guys.

**Comment by bnkai** [comment]
PR merged, closing this as completed
