### ISSUE TITLE
[renamerOnUpdate] [bug] Plugin not working for M1 Mac

### ISSUE THREAD

**Issue by brmck** [stashapp/CommunityScripts#134]
Hi, I hope I'm posting this in the right place - I'm no stranger to Stash, but having zero luck with the renamerOnUpdate plugin, it just won't work for me. Stash can _see_ the plugin and I've created a template I'd like to use, but it simply won't rename my file names on update.

Not sure if it's a Mac thing, but I'm on macOS Ventura 13.1 and running the Apple Silicone version of Stash if that helps. I'll assume it's a Python problem which is located here:

`/opt/homebrew/bin/python3`
`/usr/local/bin/python3`
`/usr/bin/python3`

Typical error log as follows...

```
023-01-04 14:54:10 Error error executing post hooks: error running plugin: fork/exec /Users/BigMac/.stash/plugins/renamerOnUpdate/python: no such file or directory
2023-01-04 14:54:32 Error error executing post hooks: error running plugin: fork/exec /Users/BigMac/.stash/plugins/renamerOnUpdate/Users/BigMac/.stash/plugins/renamerOnUpdate/python: no such file or directory
```

**Comment by brmck** [comment]
In typical fashion, it turned out to be a simple fix!

In renamerOnUpdate.yml

Change

`exec:
  **- python**
  - "{pluginDir}/renamerOnUpdate.py"`
  
  to

`exec:
  **- python3**
  - "{pluginDir}/renamerOnUpdate.py"`
  
  Dur. :)

**Comment by bnkai** [comment]
closing as resolved
