### ISSUE TITLE
More detail for the use of SQLITE Renamer for Stash

### ISSUE THREAD

**Issue by baloodusudouest** [stashapp/CommunityScripts#14]
Hi,

it is possible to have more detail, screenshot or example to know how to do it?

For exemple, i would like to have something like
Main folder/parent_studio/Studio/[Studio]-the title-date-performer1.performer2...

And at which moment it will be rename? when scrape? edit and save?

Thanks for your help!

**Comment by jthrow0451** [comment]
It updates when you write a change to the database, so marking as organized, changing any metadata and saving, etc.

It is possible to have more detail, it will require mapping more graph-ql scheme to variables in the python file, you can add them yourself if you can figure it out.

**Comment by bnkai** [comment]
Original issue was probably refering to <https://github.com/stashapp/CommunityScripts/tree/main/scripts/Sqlite_Renamer>
That one needed to run separately as a script and needs a bit of configuration of the py file.
I would use instead the newer plugins <https://github.com/stashapp/CommunityScripts/tree/main/plugins/renamer> or <https://github.com/stashapp/CommunityScripts/tree/main/plugins/renamerOnUpdate> as they are easier and safer to use.

From what i see from #37 this can be closed
