### ISSUE TITLE
Move Plex plugin "StashPlexAgent.bundle" into own repository for easier management

### ISSUE THREAD

**Issue by electblake** [stashapp/CommunityScripts#143]
I believe best practice is to allow custom plex plugins to be in their own repo, makes clones and updates easier to install and manage.

An example: [https://github.com/PAhelper/PhoenixAdult.bundle](https://github.com/PAhelper/PhoenixAdult.bundle)

If still want to keep repo here, I'd consider still breaking out `StashPlexAgent.bundle` into own repository, and git submodule it here (can be in the same location)

**Comment by electblake** [comment]
FYI, I've made updates to the bundle locally and was about to create personal repo - but pull/push upstream changes would be manual. a repo I can fork would keep within community

**Comment by DogmaDragon** [comment]
It is available on the author's repo <https://github.com/Darklyter/StashPlexAgent.bundle>

**Comment by bnkai** [comment]
@DogmaDragon should we just leave the README with the repo link? I think we should remove the actual code from this repo

**Comment by electblake** [comment]
oh, thanks! very nice

+1 on removing code from this repo, confusing and agent is outdated

**Comment by DogmaDragon** [comment]
> @DogmaDragon should we just leave the README with the repo link? I think we should remove the actual code from this repo

@bnkai it was submitted by the author <https://github.com/stashapp/CommunityScripts/pull/15>, but I agree that it makes sense to remove the 3rd party integrations from the repo. 

I updated the repo link on <https://docs.stashapp.cc/add-ons/third-party-integrations/#stashplexagentbundle>
