### ISSUE TITLE
[renamerOnUpdate] I can't figure out where I went wrong

### ISSUE THREAD

**Issue by MaltoxTv** [stashapp/CommunityScripts#144]
I am running Python 3.8, pip 23, and requests 2.28.2 so I should have all the prerequisites. I have Stash installed into a subfolder in my downloads folder, a plugin folder within that, and then finally the renamer script. Stash recognizes the script but won't even blurt out a log file let alone actually do the renaming and moving I spent hours trying to set it up to do. I've spent 3 days trying to figure this out myself but am getting nowhere, I would highly appreciate some help! I've attached my config file, hopefully with that, my stash directory info, and what programs/versions i'm using will help identify what I did wrong. Could be a simple syntax error honestly, I don't know what i'm doing or if i'm even allowed to request help here like this

I have also included a list of my current tags and the directories i'm trying to put them in. I did try to run this without the $studio_hierarchy addition when moving the videos per tags without luck either. This is a VR porn library that I'm trying to use with DeoVR so having the folder physically organized by tags, studios, and performers would be very helpful. Is there a way to get this script to create shortcuts to the videos? For instance, many videos have multiple tags so if I create a folder for every single tag then many videos will be referenced multiple times, so where does it go? Into the performer folder and a shortcut is placed in all folders that reference it. I think I have a fundamental misunderstanding of how this works... 
[RenamerOnUpdate_configexample.txt]
[Taglist2_12_2023CS.txt](https://github.com/stashapp/CommunityScripts/files/10726035/Taglist2_12_2023CS.txt)
[RenamerOnUpdate_configexample.txt](https://github.com/stashapp/CommunityScripts/files/10726044/RenamerOnUpdate_configexample.txt)
[TADCS.txt](https://github.com/stashapp/CommunityScripts/files/10726033/TADCS.txt)

**Comment by bnkai** [comment]
Discussion here <https://github.com/stashapp/stash/discussions/3435> so closing this
