### ISSUE TITLE
[renamer] and [renameonupdate] cannot launch scripts

### ISSUE THREAD

**Issue by letraitplat** [stashapp/CommunityScripts#162]
Hello,
just installed and, I think, properly configured both of those plugins.
Using Stash as a docker app on a qnap NAS.
They do show up in plugins page of stash, but whenever I try launching them, I get error messages in my logs : 

_Error running plugin task: error running plugin: fork/exec /config/plugins/renamer/python: no such file or directory_
and
_Error running plugin task: error running plugin: fork/exec /config/plugins/renamerOnUpdate/config/plugins/renamerOnUpdate/python: no such file or directory_

I'm also not getting log files, but I guess this is a side effect of the pluging not even properly launching.

Sorry if this is a newbie question, I must admit I'm still struggling to understand some features / config of this tool

Regards

**Comment by DogmaDragon** [comment]
Try setting your Python path in Settings > System > Application Paths > Python Path. 

Also you can try changing `python` to `python3` in `renamerOnUpdate.yml`.

**Comment by letraitplat** [comment]
Hello,
thanks for the answer
I'll be honest, I have no clue where to find python on my system. It's a docker based install so I also don't know wether python is included in the container or not ?

If python was missing in the container, would Stash still be able to function nevertheless ?

**Comment by letraitplat** [comment]
managed solving the issue, this can be closed
thanks

**Comment by marcaurelios** [comment]
> managed solving the issue, this can be closed thanks

How did you solve it!?
