### ISSUE TITLE
Not updating filename

### ISSUE THREAD

**Issue by kruth333** [stashapp/CommunityScripts#24]
Whenever I update a scene the plugin doesn't work and I get this message in the log:

"error executing post hooks: Error running plugin: exec: "C:\\Users\\_____\\.stash\\plugins\\renamer\\python": file does not exist"

Thanks for any help.

**Comment by jeremymeyers** [comment]
make sure you have python 3.x properly installed on your computer.  You can get it from the windows store or from python.org

**Comment by bnkai** [comment]
Issue seems to be resolved as missing/not properly installed python was probably the issue.
