### ISSUE TITLE
Instructions use wrong file name

### ISSUE THREAD

**Issue by FatDogSB** [stashapp/CommunityScripts#266]
Here is an example:
❗ Make sure to configure the plugin by editing config.py before running it ❗

But there is no 'config.py' in the repository so I spent time going through the Stash config.py until I realized the documentation might be wrong.

I believe it is called renamerOnUpdate_config.py and it is in the .stash/plugins/renamerOnUpdate/**renamerOnUpdate_config.py**

Can you please search and replace the instructions to use the correct name.

**Comment by DogmaDragon** [comment]
Updated in https://github.com/stashapp/CommunityScripts/commit/0eec56a43d6a50547b3b01b95091206ac6b4bb9b.
