### ISSUE TITLE
[VideoScrollWheel] Feature Request - Option to reverse volume direction

### ISSUE THREAD

**Issue by nishare** [stashapp/CommunityScripts#268]
What a great plugin, I love it!

Would it be possible to add an option to reverse the scroll direction for the volume? (I guess, you could also do the same for the video scroll, but the default direction is logical).

This is for those of us that use natural scrolling (started as an Apple thing, but has gained momentum elsewhere now).

Thank you for listening!

**Comment by WeedLordVegeta420** [comment]
@nishare This is actually already possible without any changes needed. You just need to go into the Plugin settings and change the Volume Scroll Speed to a negative number.

![image](https://github.com/user-attachments/assets/04c06d56-90db-4920-a818-3d0d64a1ca53)
