### ISSUE TITLE
Kodi-helper script doesn't run correctly... for me

### ISSUE THREAD

**Issue by dbldose13** [stashapp/CommunityScripts#27]
I can't seem to get this script to run. is there perhaps a more detailed explanation for a noob trying to generate strm files?

When i run this script i get an error stating 
"line 3, in <module>
import requests
modulenotfounderror: no module named 'requests' "

i'm currently running stash in docker on dsm7.
stash itself runs great. i've tried to tinker with the script to get it to work, but im not an expert with python, so i'm stuck. please let me know what i'm doing wrong.

**Comment by WithoutPants** [comment]
You don't have the python `requests` module installed.

You'll need to run `pip install requests` or `pip3 install requests`

**Comment by dbldose13** [comment]
Thank you. I managed to get it to work after making sure requests was installed.

 i feel kinda dumb that something this simple turned out to be the problem.

Thanks again.

**Comment by bnkai** [comment]
Closing as issue was resolved
