### ISSUE TITLE
PHash Duplicate Tagger: NameError: name 'log' is not defined

### ISSUE THREAD

**Issue by yoleska-dev** [stashapp/CommunityScripts#271]
024-03-06 11:12:14
Error   
Plugin returned error: exit status 1
2024-03-06 11:12:14
Error   
[Plugin / PHash Duplicate Tagger] NameError: name 'log' is not defined
2024-03-06 11:12:14
Error   
[Plugin / PHash Duplicate Tagger]     ^^^
2024-03-06 11:12:14
Error   
[Plugin / PHash Duplicate Tagger]     log.error(
2024-03-06 11:12:14
Error   
[Plugin / PHash Duplicate Tagger]   File "/root/.stash/plugins/community/phashDuplicateTagger/phashDuplicateTagger.py", line 18, in <module>
2024-03-06 11:12:14
Error   
[Plugin / PHash Duplicate Tagger] Traceback (most recent call last):
2024-03-06 11:12:14
Error   
[Plugin / PHash Duplicate Tagger] During handling of the above exception, another exception occurred:
2024-03-06 11:12:14
Error   
[Plugin / PHash Duplicate Tagger] ModuleNotFoundError: No module named 'config'
2024-03-06 11:12:14
Error   
[Plugin / PHash Duplicate Tagger]     import config
2024-03-06 11:12:14
Error   
[Plugin / PHash Duplicate Tagger]   File "/root/.stash/plugins/community/phashDuplicateTagger/phashDuplicateTagger.py", line 16, in <module>
2024-03-06 11:12:14
Error   
[Plugin / PHash Duplicate Tagger] Traceback (most recent call last):
2024-03-06 11:12:14
Error   
[Plugin / PHash Duplicate Tagger] You need to install the stashapi module. (pip install stashapp-tools)

**Comment by yoleska-dev** [comment]
This is with v25 of Stash and 0.1.3-983b28b for PHash Duplicate Tagger

**Comment by stg-annon** [comment]
>  You need to install the stashapi module. (pip install stashapp-tools)

**Comment by yoleska-dev** [comment]
I thought the same, but this is in a docker container for unraid..  no bueno.

/ # pip install stashapp-tools
error: externally-managed-environment

× This environment is externally managed

**Comment by stg-annon** [comment]
You can shell into your docker container and run `python -m pip --break-system-packages install stashapp-tools`

**Comment by yoleska-dev** [comment]
That's actually where I am. :) 

Doesn't like that arg:

/ # python -m pip --break-system-packages install stashapp-tools

Usage:   
  /usr/bin/python -m pip <command> [options]

no such option: --break-system-packages
/ #

**Comment by yoleska-dev** [comment]
This is likely a problem for the container itself.  I can open an issue for https://github.com/stashapp/stash/issues

**Comment by stg-annon** [comment]
you could also try https://github.com/feederbox826/stash-s6

**Comment by yoleska-dev** [comment]
All right, we're getting somewhere.  That worked!  I had to rename the config_exampl.py file, and then reran the tagging for [Exact] and it worked.  Thanks for the quick assist.
