### ISSUE TITLE
Error: 'set' object has no attribute 'items' when running PHASH Generate

### ISSUE THREAD

**Issue by yoleska-dev** [stashapp/CommunityScripts#273]
Stash v25, PDT version 0.1.3-983b28b

When the "Generate Scene PHASHs" is clicked from the bottom of the Plugin Tasks menu item (under Tasks), I see this error in the logs and nothing seems to happen in the GUI.  Task runs for a second, then stops.

2024-03-06T16:43:54.884435654-08:00 INF Response: 200 OK httpRequest={"proto":"HTTP/1.1","remoteIP":"127.0.0.1:60048","requestID":"d65849e13720/65Se712tpy-010214","requestMethod":"POST","requestPath":"/graphql","requestURL":"http://127.0.0.1:9999/graphql"} httpResponse={"bytes":32213,"elapsed":7.123696,"status":200} service=stash
ERRO[2024-03-06 16:43:54] [Plugin / PHash Duplicate Tagger] Traceback (most recent call last): 
ERRO[2024-03-06 16:43:54] [Plugin / PHash Duplicate Tagger]   File "/root/.stash/plugins/community/phashDuplicateTagger/phashDuplicateTagger.py", line 293, in <module> 
ERRO[2024-03-06 16:43:54] [Plugin / PHash Duplicate Tagger]     main() 
ERRO[2024-03-06 16:43:54] [Plugin / PHash Duplicate Tagger]   File "/root/.stash/plugins/community/phashDuplicateTagger/phashDuplicateTagger.py", line 62, in main 
ERRO[2024-03-06 16:43:54] [Plugin / PHash Duplicate Tagger]     generate_phash() 
ERRO[2024-03-06 16:43:54] [Plugin / PHash Duplicate Tagger]   File "/root/.stash/plugins/community/phashDuplicateTagger/phashDuplicateTagger.py", line 286, in generate_phash 
ERRO[2024-03-06 16:43:54] [Plugin / PHash Duplicate Tagger]     stash._callGraphQL(query, variables) 
ERRO[2024-03-06 16:43:54] [Plugin / PHash Duplicate Tagger]   File "/usr/lib/python3.11/site-packages/stashapi/classes.py", line 222, in _callGraphQL 
ERRO[2024-03-06 16:43:54] [Plugin / PHash Duplicate Tagger]     serialize_dict(variables) 
ERRO[2024-03-06 16:43:54] [Plugin / PHash Duplicate Tagger]   File "/usr/lib/python3.11/site-packages/stashapi/classes.py", line 365, in serialize_dict 
ERRO[2024-03-06 16:43:54] [Plugin / PHash Duplicate Tagger]     for key, value in input_dict.items(): 
ERRO[2024-03-06 16:43:54] [Plugin / PHash Duplicate Tagger]                       ^^^^^^^^^^^^^^^^ 
ERRO[2024-03-06 16:43:54] [Plugin / PHash Duplicate Tagger] AttributeError: 'set' object has no attribute 'items' 
ERRO[2024-03-06 16:43:54] Plugin returned error: exit status 1

**Comment by stg-annon** [comment]
#274

**Comment by yoleska-dev** [comment]
Dupe, thanks!

**Comment by stg-annon** [comment]
@Maista6969 @DogmaDragon good to close
