### ISSUE TITLE
[renamerOnUpdate] Deletes characters that are in the template

### ISSUE THREAD

**Issue by coscosname** [stashapp/CommunityScripts#28]
Deletes characters that are in the template if one of the values is empty.
e.g.
```python
filename_template = "[$studio] $date _ $title"
scene_information["studio"] = "studio1"
scene_information["date"] = ""
scene_information["title"] = "title1"
```

In this case we get
```
[studio1] title1
```
instead of
```
[studio1] - title1
```
This applies to characters
```
- and _
```

https://github.com/stashapp/CommunityScripts/blob/975d179d8b02feeb351edc5658abd42e5b7a0bd7/plugins/renamerOnUpdate/renamerOnUpdate.py#L182

**Comment by bnkai** [comment]
Relevant PR merged. Closing.
