### ISSUE TITLE
[VideoScrollwhee] Not functioning after June 1 update

### ISSUE THREAD

**Issue by nishare** [stashapp/CommunityScripts#320]
The pluging no longer works at all. 

In the Plugins settings, when activating Volume (and / or adjusting the speed for volume), it resets itself to off.

The scroll scrubbing doesn't seem to work either (but not something I have used much in the past - but I live for the volumen scroll).

**Comment by DogmaDragon** [comment]
@feederbox826 could you take a look?

**Comment by feederbox826** [comment]
Having a look - It doesn't use any new queries and the webui state is not changed at all...

**Comment by feederbox826** [comment]
I'm able to replicate this in v0.25.1 but not in develop, which explains the oversight. Looking into it!
