### ISSUE TITLE
ReferenceError: csLib is not defined

### ISSUE THREAD

**Issue by Tscherno** [stashapp/CommunityScripts#328]
I get the error "ReferenceError: csLib is not defined" for two plugins since a few days:
![grafik](https://github.com/stashapp/CommunityScripts/assets/5594674/6be03d59-80c2-4b49-80ec-fe0f7e51012e)

![grafik](https://github.com/stashapp/CommunityScripts/assets/5594674/245413c1-532f-4dcd-a03a-b3dc3ae41c02)

![grafik](https://github.com/stashapp/CommunityScripts/assets/5594674/4f487929-6da1-4778-841d-1ddd37b4ed30)

**Comment by feederbox826** [comment]
You need to install https://github.com/stashapp/CommunityScripts/tree/main/plugins/CommunityScriptsUILibrary, which should have been installed automatically from the plugin manager
