### ISSUE TITLE
[renamerOnUpdate] All scenes are placed in path with the same performer

### ISSUE THREAD

**Issue by nothing2obvi** [stashapp/CommunityScripts#332]
v2.5

My path tag template is:
```
"rename_test": r"/data/organized/$performer/"
```

Let's say I have 3 scenes:
- scene 1 (performer-1)
- scene 2 (performer-2)
- scene 3 (performer-3)

Despite my path tag template, all scenes get placed in `/data/organized/performer-1`.

Am I doing something wrong? Thanks.

**Comment by prattman** [comment]
I am looking for the same thing, organise by performer. Can anyone help

**Comment by nothing2obvi** [comment]
@prattman Find anything?

**Comment by phhemberg** [comment]
@prattman @nothing2obvi  Did you get it to work or else i may be able to help you.

**Comment by nothing2obvi** [comment]
I'm not sure what I did, but I forgot about this and it just works now.
