### ISSUE TITLE
[stashRealbooru] Syntax error in script

### ISSUE THREAD

**Issue by HBir** [stashapp/CommunityScripts#344]
https://github.com/stashapp/CommunityScripts/blob/0aafb805352bcbd52e66db65388beaac39f1bccf/plugins/stashRealbooru/stash-realbooru.js#L16

This `I;` breaks the script.
Simply removing it fixes the issue.

**Comment by DogmaDragon** [comment]
Not sure if the error is significant, but it works without any issues on my end with it present.

**Comment by HBir** [comment]
When running the script on an image I get the error and it gets stuck on the spinning animation. Seems to still work on scenes though.

```
javascript:16 Uncaught (in promise) ReferenceError: I is not defined
    at getTagsForImage (javascript:16:5)
    at HTMLButtonElement.save (javascript:2020:32)
```

**Comment by DogmaDragon** [comment]
Weird as it doesn't report any errors for me. But it works for me either way, so I don't see an issue with removing it. 

@feederbox826 you were the one that introduced this. Is this just a typo, or are we missing something?

**Comment by feederbox826** [comment]
git blame says yes - https://github.com/stashapp/CommunityScripts/commit/adade5e7ed8d03e200294639ccb632d1ea425e52#diff-3e838cfd40704d4318d6d72308bcb8f4278b35cc5541c8a6190246181080f8e6R16

Must have been a typo after testing
