### ISSUE TITLE
Cannot add comma as performer separator

### ISSUE THREAD

**Issue by JayJiggy** [stashapp/CommunityScripts#35]
I have set "performer_splitchar" to many characters, and all work except a comma. Is there any reason why a comma cannot be used here?

**Comment by Krish-bhardwaj** [comment]
Hi can you explain your project issue , i would like to contribute to your project

**Comment by JayJiggy** [comment]
Using the renamerOnUpdate, I cannot get it to accept a comma as a performer name separator. I can use any other char that I've tried, including a period, but it will not put a comma

**Comment by Krish-bhardwaj** [comment]
can u send me code  and output SS and where is this file

**Comment by Krish-bhardwaj** [comment]
> Using the renamerOnUpdate, I cannot get it to accept a comma as a performer name separator. I can use any other char that I've tried, including a period, but it will not put a comma

insted of using comma u can use ASCII char for ( , ) use ord(44) (ascii char for , is 44)
https://www.cs.cmu.edu/~pattis/15-1XX/common/handouts/ascii.html

**Comment by JayJiggy** [comment]
I don't know what output SS is. I'm telling you, everything works but "," (comma). I've tried dash, underscore, letter, numbers, period, all work but comma, so it's not the code or anything else. I've even put ",. " and "., " and either way, I get "performer. Performer", a period, no comma

**Comment by JayJiggy** [comment]
if I type "ord(44)" in that space, it puts those exact characters in the filename

**Comment by Krish-bhardwaj** [comment]
> I don't know what output SS is. I'm telling you, everything works but "," (comma). I've tried dash, underscore, letter, numbers, period, all work but comma, so it's not the code or anything else. I've even put ",. " and "., " and either way, I get "performer. Performer", a period, no comma

SS means screenshot !
try ascii char

**Comment by Krish-bhardwaj** [comment]
> if I type "ord(44)" in that space, it puts those exact characters in the filename
then what do u want

**Comment by Krish-bhardwaj** [comment]
o u are tring to put comma in filename?

**Comment by JayJiggy** [comment]
I want a comma to separate the performers names

**Comment by Krish-bhardwaj** [comment]
but u can't put , in file name ig

**Comment by JayJiggy** [comment]
![Untitled](https://user-images.githubusercontent.com/97656590/149279152-cfb57baf-bcbd-4987-8180-e4ab6c6e0725.png)

**Comment by JayJiggy** [comment]
why would I not be able to use a comma in the filename? That is not a windows limitation

**Comment by Krish-bhardwaj** [comment]
https://meet.google.com/gja-efvb-yqw join in !

**Comment by Krish-bhardwaj** [comment]
are u joining

**Comment by JayJiggy** [comment]
a video call? why do we need video?

**Comment by Krish-bhardwaj** [comment]
u share your screen

**Comment by JayJiggy** [comment]
I'm not using the same pc to talk to you, I can take screenshots and transfer to this pc via LAN

**Comment by Krish-bhardwaj** [comment]
np i am looking your code

**Comment by JayJiggy** [comment]
Like I said, it works fine for anything but a comma, so I don't see how unless this is designed not to work with a comma for some reason. What character makes more sense to separate multiple names than a comma? Doesn't make any sense to me, but I'm not a code writer

**Comment by Krish-bhardwaj** [comment]
ok so u use "_" or " | " it will work fine it hardly matters

**Comment by Krish-bhardwaj** [comment]
![image](https://user-images.githubusercontent.com/72294477/149281333-9f965f01-6444-4de2-a958-f9d275ee2dc0.png)

**Comment by Krish-bhardwaj** [comment]
avoid using special char

**Comment by Krish-bhardwaj** [comment]
if u are convinced close this issue

**Comment by JayJiggy** [comment]
To whom does it "hardly matter"? It matters to me. I have many hundreds, if not thousands of files already organized this way, so why do I need to change it for an arbitrary error? Seems to me the error should be fixed instead of saying don't do what is fine to do bc there is an unexplained problem. And every other character listed in your "stay away" group works, so why is there a prejudice against commas? Thanks for your help, I will look elsewhere for a solution.

**Comment by JayJiggy** [comment]
parenthesis are used in the examples of how to format, so an aversion to "unwanted characters" doesn't seem to make sense to me to explain the issue

**Comment by bnkai** [comment]
https://github.com/stashapp/CommunityScripts/blob/975d179d8b02feeb351edc5658abd42e5b7a0bd7/plugins/renamerOnUpdate/renamerOnUpdate.py#L373
Adjust the regex in the following line by removing the comma and it should work

**Comment by JayJiggy** [comment]
I don't know where to look for that. Is that the windows registry?

**Comment by bnkai** [comment]
"renamerOnUpdate.py" the plugin python file you have in your stash plugins directory

**Comment by JayJiggy** [comment]
Yes, this worked. TYVM sir
