### ISSUE TITLE
[Hot Cards] rating precision broken

### ISSUE THREAD

**Issue by obatzdamelt** [stashapp/CommunityScripts#364]
The multi styling feature in the latest release is great. Unfortunately it seems to have broken ratings if using quarter/half precision.

Previously a configuration such as this worked `r_4.25_hot` Now you must drop the decimal even if not using multi.

These do not work
`r_4.25_hot`, `r_4.25/3_hot/default`

These do
`r_4_hot`, `r_4/3_hot/default`

**Comment by DogmaDragon** [comment]
@HandyRandyx

**Comment by HandyRandyx** [comment]
When using tenths precision, use the 6-100 range, in this case:

´r_4.25_hot´ = ´r_85_hot´
´r_4.25/3_hot/default´ = ´r_85/60_hot/default´

Make sure to also have the Rating Threshold option in the 6-100 range.
