### ISSUE TITLE
renamertask issue

### ISSUE THREAD

**Issue by baloodusudouest** [stashapp/CommunityScripts#37]
Hi, i try the renamer, and when i do a dry run, he find the one with the tag i want, dry rename it good (according to the txt files generated), and when i try to run on the dry ones, i have this issue.

Can you help me? @Belleyy 

022-01-18 23:27:24
Error   
Plugin returned error: exit status 1
2022-01-18 23:27:24
Error   
[Plugin / renamerTask] TypeError: string indices must be integers
2022-01-18 23:27:24
Error   
[Plugin / renamerTask]     msg = renamer(scene["id"])
2022-01-18 23:27:24
Error   
[Plugin / renamerTask]   File "/root/.stash/plugins/renamer/renamerTask.py", line 619, in <module>
2022-01-18 23:27:24
Error   
[Plugin / renamerTask] Traceback (most recent call last):
2022-01-18 23:26:21
Info    
[Plugin / renamerTask] Took 0 seconds
2022-01-18 23:26:21
Info    
[Plugin / renamerTask] [DRY-RUN] There wil be 7 file(s) changed. Check /root/.stash/plugins/renamer/renamer_scan.txt for more details

**Comment by throwawaynate** [comment]
just tried the plugin for the first time and had the exact same issue.  Dry run works perfectly and shows the correct new names for files.  When I run the `Process scanned scene from Dry-Run task` it fails with the following log entries

```
2022-01-20 12:21:35
Error   
Plugin returned error: exit status 1
2022-01-20 12:21:35
Error   
[Plugin / renamerTask] TypeError: string indices must be integers
2022-01-20 12:21:35
Error   
[Plugin / renamerTask]     msg = renamer(scene["id"])
2022-01-20 12:21:35
Error   
[Plugin / renamerTask] Traceback (most recent call last):
2022-01-20 12:21:35
Error   
[Plugin / renamerTask]   File "/root/.stash/plugins/CommunityScripts/plugins/renamer/renamerTask.py", line 619, in <module>
2022-01-20 12:21:35
Debug   
[Plugin / renamerTask] Count scenes: 9
2022-01-20 12:21:35
Debug   
[Plugin / renamerTask] --Starting Plugin 'Renammer'--
```

**Comment by bnkai** [comment]
@throwawaynate @baloodusudouest 
you can try changing line `608` in `renamerTask.py`
from
```py
                scenes["scenes"].append(scene_id_file)
```
to
```py
                scenes["scenes"].append({"id": scene_id_file})
```

**Comment by baloodusudouest** [comment]
ok, i've done the change, the txt file for dry is still good, but i have now
2022-01-20 22:47:59
Debug   
Plugin returned: Successful!
2022-01-20 22:47:59
Info    
[Plugin / renamerTask] Took 5 seconds
2022-01-20 22:47:59
Debug   
[Plugin / renamerTask] No template for this scene.
2022-01-20 22:47:59
Debug   
[Plugin / renamerTask] No template for this scene.
2022-01-20 22:47:59
Debug   
[Plugin / renamerTask] No template for this scene.
2022-01-20 22:47:59
Debug   
[Plugin / renamerTask] No template for this scene.
2022-01-20 22:47:58
Debug   
[Plugin / renamerTask] No template for this scene.
2022-01-20 22:47:58
Debug   
[Plugin / renamerTask] No template for this scene.
2022-01-20 22:47:58
Debug   
[Plugin / renamerTask] No template for this scene.
2022-01-20 22:47:56
Debug   
[Plugin / renamerTask] No template for this scene.
2022-01-20 22:47:56
Debug   
[Plugin / renamerTask] No template for this scene.
2022-01-20 22:47:56
Debug   
[Plugin / renamerTask] No template for this scene.
2022-01-20 22:47:56
Debug   
[Plugin / renamerTask] Count scenes: 10
2022-01-20 22:47:54
Trace   
SQL: SELECT DISTINCT scenes.id FROM scenes ORDER BY scenes.updated_at DESC, bitrate DESC, framerate DESC, scenes.rating DESC, scenes.duration DESC LIMIT 10 OFFSET 0 , args: []
2022-01-20 22:47:53
Debug   
[Plugin / renamerTask] --Starting Plugin 'Renammer'--

[config.txt](https://github.com/stashapp/CommunityScripts/files/7908707/config.txt)
here my config file (i put on txt because .py are not allowed)

**Comment by throwawaynate** [comment]
@bnkai That fix, editing line 608 fixed the issue for me.  

@baloodusudouest I think you need to edit the config file as described in the Readme.

**Comment by baloodusudouest** [comment]
thanks @throwawaynate i change the config file like the previous version, but using the protocol from the readme it's work!
