### ISSUE TITLE
[FileMonitor] dying on ssl errors?

### ISSUE THREAD

**Issue by MrRandoMan** [stashapp/CommunityScripts#380]
Hi there. I think FileMonitor is having a hard time connecting to stash's with ssl enabled.

time="2024-07-31 03:43:17" level=error msg="[Plugin / FileMonitor] StdInRead={\"server_connection\":{\"Scheme\":\"https\",\"Host\":\"0.0.0.0\",\"Port\":443,\"SessionCookie\":{\"Name\":\"session\",\"Value\":\"MTcyMjQxMTc5NnxEdi1CQkFFQ180SUFBUkFCRUFBQVpfLUNBQUlHYzNSeWFXNW5EQWdBQm5WelpYSkpSQVp6ZEhKcGJtY01BZ0FBQm5OMGNtbHVad3dWQUJOMmFYTnBkR1ZrVUd4MVoybHVjMGh2YjJ0ekcxdGRjMlZ6YzJsdmJpNVdhWE5wZEdWa1VHeDFaMmx1U0c5dmFfLUZBZ0VDXzRZQUFmLUVBQUE1XzRNREFRRVJWbWx6YVhSbFpGQnNkV2RwYmtodmIyc0JfNFFBQVFJQkNGQnNkV2RwYmtsRUFRd0FBUWhJYjI5clZIbHdaUUVNQUFBQUJmLUdBZ0FBfPPtY4XH9U-TYzX7DWwLWknm22tX-tGHsxnlHkvqtrpZ\",\"Path\":\"\",\"Domain\":\"\",\"Expires\":\"0001-01-01T00:00:00Z\",\"RawExpires\":\"\",\"MaxAge\":0,\"Secure\":false,\"HttpOnly\":false,\"SameSite\":0,\"Raw\":\"\",\"Unparsed\":null},\"Dir\":\"C:\\\\progs\\\\stash\",\"PluginDir\":\"plugins\\\\community\\\\filemonitor\"},\"args\":{\"mode\":\"start_library_monitor\"}} (len(sys.argv)=1)"
time="2024-07-31 03:43:17" level=error msg="[Plugin / FileMonitor] Could not connect to Stash at https://127.0.0.1:443/graphql"
time="2024-07-31 03:43:17" level=error msg="[Plugin / FileMonitor] HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))"

**Comment by DogmaDragon** [comment]
@David-Maisonave mentioning the author

**Comment by feederbox826** [comment]
seems to be upstream in stashapi as requests is unused @stg-annon

**Comment by David-Maisonave** [comment]
> seems to be upstream in stashapi as requests is unused @stg-annon

I'm working on an updated version where I've already removed requests and the following unused imports:
```
import time
import shutil
import fileinput
import hashlib
import stashapi.log as log # Importing stashapi.log as log for critical events ONLY
```
But are you saying having the unused imports is causing the issue, or not calling graphql_request is the issue?

**Comment by David-Maisonave** [comment]
> Hi there. I think FileMonitor is having a hard time connecting to stash's with ssl enabled.

- Does your stash use the default URL (http://localhost:9999)?
- Are you calling FileMonitor as a plugin, or calling it in command line mode?
  - If calling in the command line mode, and if you're not using default URL, did you populate the filemonitor_config.py with the correct URL details?
```
    # The following fields are ONLY used when running FileMonitor in script mode
    "endpoint_Scheme" : "http", 
    "endpoint_Host" : "0.0.0.0", 
    "endpoint_Port" : 9999,
```
- Can you please enable [Debug Tracing] in the UI, and get logging details from **stash\plugins\FileMonitor\filemonitor.log**?
  - ![FileMonitor_DebugTracing](https://github.com/user-attachments/assets/08b78119-8c3e-4c14-81ea-1b64b3abf989)

**Comment by feederbox826** [comment]
> But are you saying having the unused imports is causing the issue, or not calling graphql_request is the issue?

neither is the issue, your http interface is through stashapi which still implements https verification. you'll have to rewrite it without stashapi and only requests if you want to solve it on your end

**Comment by David-Maisonave** [comment]
> neither is the issue, your http interface is through stashapi which still implements https verification. you'll have to rewrite it without stashapi and only requests if you want to solve it on your end

Are you saying stashapi doesn't work with ssl enabled?

**Comment by stg-annon** [comment]
> seems to be upstream in stashapi as requests is unused @stg-annon

you would need to change the ssl verify flag in the session to ignore self signed certs, `stash.s.verify = False`

**Comment by stg-annon** [comment]
> > neither is the issue, your http interface is through stashapi which still implements https verification. you'll have to rewrite it without stashapi and only requests if you want to solve it on your end
> 
> Are you saying stashapi doesn't work with ssl enabled?

it does this individual just has a self signed cert for SSL so not a verified cert from a certificate authority think this warning 
![image](https://github.com/user-attachments/assets/45d4d45e-c930-4f47-b6f0-621727c01a4a)


you can disable it with a flag

**Comment by stg-annon** [comment]
it would need to be early on, now that I think about it it may need to be in the beginning of the init as stashapi now does a couple of calls during the init process, I'll add a flag for it there

**Comment by stg-annon** [comment]
> That said I found another plugin that I think has the same issue. (Tho I don't think they're using stashapi)

its quite possible `requests` is quite popular and the verify flag is by default True so unless they also specify it it will likely have the same problem

**Comment by David-Maisonave** [comment]
> For what its worth if I recall correctly I needed a host name cert to make upnp\dlna\android\vlc a lot less ornery. Considering stash's use case, I think most user ssl certs are going to be self signed anyhow, eh?

**IMHO**, most users are not going to use self signed cert, because most users are not going to use ssl for a local setup.

If you don't mine me asking, what's the use-case for using ssl on Stash (with self signed cert) in a local setup?

**Comment by feederbox826** [comment]
> published with v0.2.48

already resolved upstream

**Comment by David-Maisonave** [comment]
> (Note this is from stash.log as plugins\community\filemonitor\filemonitor.log is empty.)
I just installed clean version of FileMonitor from CommunityScripts, and the logging works. The file gets created and populated. Even with [Debug Tracing] disabled, some minimal logging occurs.

**Nothing** gets log to stash.log from FileMonitor. That's to avoid cluttering stash.log, which could happen if the user dumps thousands of files in a monitored path.
I did mean to log exceptions in stash.log, but I see I forgot to add that code.  Will add it on the next version.

I'm really concerned that you're not getting any logging in filemonitor.log, and I like to see if we can figure out why.

- What Windows version are you running?  
  - I'm assuming is Windows since there's a "C:\" listed in your opening comment.  Please correct me if I'm wrong.
- Are you looking in the following folder?
  - `C:\Users\[MyUserName]\.stash\plugins\community\filemonitor`
  - or in your case `C:\progs\stash\plugins\community\filemonitor`
- Did you refresh the file on the program you're using to view the file content?
- Does the filemonitor folder have read/write privileges for Stash?
- What happens if you delete filemonitor.log?  Does it get recreated when **restarting** the FileMonitor task [**Start Library Monitor**]?

This version of FileMonitor is a beta version, and I'm already working on some improvements.
Because of this logging issue, I'm going to add a UI option that when enabled, will send info logging to stash.log.

**Comment by David-Maisonave** [comment]
> already resolved upstream

If resolved in v0.2.48, should I include that as minimum version in the requirements.txt file?
```
stashapp-tools >= 0.2.48
pyYAML
watchdog
```

**Comment by David-Maisonave** [comment]
> it's logging now, now that FM is running.
> and FM is bailing too early to have ever written to its own debug log.

Thanks for the update.

**Comment by David-Maisonave** [comment]
Hi [MrRandoMan](https://github.com/MrRandoMan),
If this issue has been addressed, can you please close it? 😃


Thanks
