### ISSUE TITLE
[tagGraph] choking on self signed ssl

### ISSUE THREAD

**Issue by MrRandoMan** [stashapp/CommunityScripts#382]
I think this choking on ssl certs (self signed)

```
time="2024-08-01 05:57:37" level=error msg="[Plugin / Tag Graph] Could not connect to Stash at https://localhost:443/graphql"
```

See also #380

**Comment by DogmaDragon** [comment]
Plugin is not from this repository. See https://github.com/stg-annon/StashScripts/tree/main/plugins/tagGraph
