### ISSUE TITLE
Get Task Queue List

### ISSUE THREAD

**Issue by David-Maisonave** [stashapp/CommunityScripts#386]
How can a plugin get a list of task in the queue?
Or how can the plugin determine if anything has been added to the task queue?

I have a plugin [FileMonitor](https://github.com/David-Maisonave/Axter-Stash/tree/main/plugins/FileMonitor), which for the most part, stays in the task queue when it's run as a plugin. I want to be able to have it exit the task as soon as it detects a task has been added to the task queue.
![FileMonitor_OnTaskQueue_2](https://github.com/user-attachments/assets/eaa1c442-eb6c-40d4-92d5-0196c2a18cca)

I appreciate any help with this.
Thanks

**Comment by stg-annon** [comment]
you would be looking for the `FindJob` query I don't think there is a hook for this so you would have to periodically check it.

However it would probably make more sense to run your own service that communicates with stash, and if you wanted to control it from the stash UI you would create a plugin that just sends tasks to the service to tell it what to do

**Comment by David-Maisonave** [comment]
> you would be looking for the FindJob query I don't think there is a hook for this so you would have to periodically check it.

Don't you need a job ID to use find_job?
`def find_job(self, job_id):`

I can make it work with a periodic check. I just need a way to query without any details of the job.

> However it would probably make more sense to run your own service that communicates with stash

My plugin already has the option to do that.  It can run in command line mode, and then I don't have to worry about the task queue. But I don't like running it that way for several reasons.
1. It's another command line window that I have to leave open while it's running.
2. It's not user friendly.  I rather use the plugin method where I can just click one button to start it.

**Comment by David-Maisonave** [comment]
As a temporary workaround, I'm looping through all the ID's until I get None.
``` python
def isJobRunning():
    i = 1
    while i < 999:
        jobDetails = plugin.STASH_INTERFACE.find_job(i)
        if jobDetails:
            if jobDetails['status'] == "RUNNING" and jobDetails['description'] != "Running plugin task: Start Library Monitor":
                return True
        else:
            break
        i += 1    
    return False
```

Is there a better approach to getting jobs that are running?

**Comment by David-Maisonave** [comment]
I notice every time find_job is call, I see the following in the plugin log file: `http://127.0.0.1:9999 "POST /graphql HTTP/11" 200 199`

Example logging:

```
[240806 14:48:54] http://127.0.0.1:9999 "POST /graphql HTTP/11" 200 199
[240806 14:48:54] [LN:87] TRACE: (Job ID(1)={'id': '1', 'status': 'CANCELLED', 'subTasks': None, 'description': 'Generating...', 'progress': 0.16, 'startTime': '2024-08-06T14:43:49.3770992-04:00', 'endTime': '2024-08-06T14:44:27.385267-04:00', 'addTime': '2024-08-06T14:43:49.3766646-04:00', 'error': None})
[240806 14:48:54] http://127.0.0.1:9999 "POST /graphql HTTP/11" 200 223
[240806 14:48:54] [LN:87] TRACE: (Job ID(2)={'id': '2', 'status': 'CANCELLED', 'subTasks': None, 'description': 'Running plugin task: Start Library Monitor', 'progress': 0, 'startTime': '2024-08-06T14:44:27.385267-04:00', 'endTime': '2024-08-06T14:47:08.7536005-04:00', 'addTime': '2024-08-06T14:44:19.2610252-04:00', 'error': None})
[240806 14:48:54] http://127.0.0.1:9999 "POST /graphql HTTP/11" 200 176
[240806 14:48:54] [LN:87] TRACE: (Job ID(3)={'id': '3', 'status': 'CANCELLED', 'subTasks': None, 'description': 'Generating...', 'progress': 0, 'startTime': None, 'endTime': None, 'addTime': '2024-08-06T14:45:50.9646154-04:00', 'error': None})
[240806 14:48:54] http://127.0.0.1:9999 "POST /graphql HTTP/11" 200 200
[240806 14:48:54] [LN:87] TRACE: (Job ID(4)={'id': '4', 'status': 'RUNNING', 'subTasks': None, 'description': 'Running plugin task: Start Library Monitor', 'progress': 0, 'startTime': '2024-08-06T14:47:54.3226014-04:00', 'endTime': None, 'addTime': '2024-08-06T14:47:54.3226014-04:00', 'error': None})
[240806 14:48:54] http://127.0.0.1:9999 "POST /graphql HTTP/11" 200 49
```

The log line with **TRACE** is the script's logging, and the log lines with the URL I believe is coming out of the stashapp find_job.
Is that a bug?
Is there anyway to block it from logging?

**Comment by stg-annon** [comment]
yes my mistake `FindJob` would be to check on the job after getting its ID you would need the ID from the `jobQueue` query

**Comment by David-Maisonave** [comment]
> yes my mistake FindJob would be to check on the job after getting its ID you would need the ID from the jobQueue query

I could not find jobQueue in the stashapi library. Is there some example code for calling a jobQueue query?

**Comment by stg-annon** [comment]
indeed it is not in stashapi yet, it does not cover all the functions from the GQL API, however you can implement any of the GQL functions directly with call_GQL

 the job id is usually returned by that call that invoked the task so you could use that as well

**Comment by David-Maisonave** [comment]
> indeed it is not in stashapi yet, it does not cover all the functions from the GQL API, however you can implement any of the GQL functions directly with call_GQL

Thanks.
I'm not very familiar with implementing GQL API, but I guess I'm going to have to force myself to learn it.

On a related topic, do I also have to use call_GQL to start a backup job?
I was looking at [stashapp API](https://docs.stashapp.cc/networking/api/), and it listed the following:
```
{
  "query": "mutation { backupDatabase(input: {download: false})}"
}
```

Am I correct in assuming there's no stashapp function for running a backup, and I'm going to have to use above query to execute a backup?

I'm adding a reoccurring scheduler to FileMonitor, and I want to include the backup task in the scheduler.

**Comment by David-Maisonave** [comment]
Disregard previous question. I got the backup working with the following query:
`plugin.STASH_INTERFACE.call_GQL("mutation { backupDatabase(input: {download: false})}")`

Thanks for all the help.
Closing question.
