### ISSUE TITLE
Adding StashPluginHelper to stashapp

### ISSUE THREAD

**Issue by David-Maisonave** [stashapp/CommunityScripts#387]
Consider adding [StashPluginHelper](https://github.com/David-Maisonave/Axter-Stash/tree/main/StashPluginHelper) to stashapp library.

After I started working on my third plugin, I notice I was using the same chunk of code in all of my plugin code. So I put the code into a reusable wrapper **StashPluginHelper** class.

IMHO, I think other plugin could find this class useful.
See the link [StashPluginHelper](https://github.com/David-Maisonave/Axter-Stash/tree/main/StashPluginHelper)  which list its features and usage.

**Comment by DogmaDragon** [comment]
Unrelated to this repository. You might want to open an issue in [stg-annon/stashapi](https://github.com/stg-annon/stashapi).
