### ISSUE TITLE
[PythonToolsInstaller] Wrong Path

### ISSUE THREAD

**Issue by elaksenr** [stashapp/CommunityScripts#388]
I've installed the `Python Tools Installer` plugin, but it fails to install the python tools themselves.

Steps:
1- Go to settings
2- Go to Tasks
3- Scroll down to Plugin Tasks
4- Select the Install button under "Python Tools Installer"
5- Stash will display the task as running for a few seconds and then nothing. Going to the logs shows the error below.

```
Error   Plugin returned error: exit status 1
Error   [Plugin / Python Tools Installer] FileNotFoundError: [Errno 2] No such file or directory: '/root/.stash/plugins/community/PythonToolsInstaller/venv/lib/python3.11/site-packages'
```

**Comment by feederbox826** [comment]
this was because of an update to python3.12 - fixed in https://github.com/stashapp/CommunityScripts/commit/dc0b6c6271be0e15935dfc229c19cf880b3eade3#diff-5ae115e05c1c0b174174ade6da45e50d1ae6bd56f171f0022279341ec5e699e1
