### ISSUE TITLE
Adding methods to stashapp

### ISSUE THREAD

**Issue by David-Maisonave** [stashapp/CommunityScripts#391]
This post actually started out as a question, until I figured out the bug in my code while posting the logging.
So that other developers don't have to spend time reinventing the wheel, can the following 2 functions get added to stashapp.py?
```
	def metadata_autotag(self, paths:list=[], dry_run=False):
		if not paths:
			return

		query = """
		mutation MetadataAutoTag($input:AutoTagMetadataInput!) {
			metadataAutoTag(input: $input)
		}
		"""

		metadata_autotag_input = {
			"paths": paths
		}
		result = self.call_GQL(query, {"input": metadata_autotag_input})
		return result

	def backup_database(self):
		result = self.call_GQL("mutation { backupDatabase(input: {download: false})}")
		return result
```

I added it to my copy of stashapp.py, but I'm worried that I'll loose the changes if I upgrade stashapp.

I'll create a pull request if there's willingness to receive the functions.

**Comment by DogmaDragon** [comment]
Unrelated to this repository. You might want to open an issue in https://github.com/stg-annon/stashapi.

**Comment by stg-annon** [comment]
just answering here if someone comes across it, you can just extend the class with any functions you might want to add

example
```py

from stashapi.stashapp import StashInterface

class MyStashInterface(StashInterface):
	def metadata_autotag(self, paths:list=[], dry_run=False):
		if not paths:
			return

		query = """
		mutation MetadataAutoTag($input:AutoTagMetadataInput!) {
			metadataAutoTag(input: $input)
		}
		"""

		metadata_autotag_input = {
			"paths": paths
		}
		result = self.call_GQL(query, {"input": metadata_autotag_input})
		return result

	def backup_database(self):
		result = self.call_GQL("mutation { backupDatabase(input: {download: false})}")
		return result

stash = MyStashInterface()
```

**Comment by David-Maisonave** [comment]
> just answering here if someone comes across it, you can just extend the class with any functions you might want to add

Thanks for the example.  I've already created a pull request at [stashapi](https://github.com/stg-annon/stashapi).
But I'll use the extended class as a temporary workaround until (and if) the changes get added to stashapi.
