### ISSUE TITLE
[renamerOnUpdate] Option to prevent file renaming

### ISSUE THREAD

**Issue by HeavyDinosaur** [stashapp/CommunityScripts#40]
Hi,
I am trying to figure out how to prevent a filename change if it belongs to a particular studio.

```
# Adjust the below if you want to use studio names instead of tags for the renaming templates
studio_templates = {
        "Adam & Eve": "$studio - $title",
        "Brazzers": None

}

# Change to True to use the default template if no specific tag/studio is found
use_default_template = True
# Default template, adjust as needed
default_template = "$studio - $title"
```
For example, my current understanding is:

- Scenario1: The scene belongs to the "Adam & Eve" studio it would rename the file according to the fields.
- Scenario2: If there is no explicit studio template defined it will use the default template.

Current Issue:

- Scenario3: If the file belongs to the Brazzers studio, I do not want to rename it. I tried using `None` and `''`. However it doesn't seem to work.
- Scenario4: If the file doesn't belong to a studio, I do not want to rename it.

**Comment by bnkai** [comment]
Scenario 1 seems correct to me
Scenario 2 if there is no explicit studio template AND the file has not been tagged with a template tag (or no template tags are configured) then it will only be renamed if the use_default_template is set to True
For scenario 3 from my understanding you cannot prevent anything by studio names. You can only do the inverse, rename a file if it belongs to  a specific studio.
For scenario 4 this should work provided that the file is not tagged with your configured template tags AND the use_default_template is set  to False.

**Comment by HeavyDinosaur** [comment]
thanks
