### ISSUE TITLE
❓[RFC] Post information to the Task Queue

### ISSUE THREAD

**Issue by David-Maisonave** [stashapp/CommunityScripts#419]
How can a plugin task output data to the Task Queue the way a Scan task does so?
Example:
![TaskQueueScanningDisplay](https://github.com/user-attachments/assets/cc5e0e85-b8e7-4fd5-849f-7cd63496d33d)

**Comment by feederbox826** [comment]
not really an RFC, please go to the discord for support
your answer is here https://docs.stashapp.cc/in-app-manual/plugins/embeddedplugins/#javascript-api

**Comment by DogmaDragon** [comment]
@David-Maisonave we also have a Matrix space https://docs.stashapp.cc/matrix/. It's bridged to Discord, so you can still reach the wider audience. Alternatively, you can use [Discussions](https://github.com/stashapp/stash/discussions/categories/q-a).

It's not so much the lack of features, but more that this is an adult project, so some people don't want to associate their GitHub account with it. As a result, it limits the number of people that can answer any questions.
