### ISSUE TITLE
[stash-watcher] script broken by watchdog 5.0.0

### ISSUE THREAD

**Issue by YonderboyLupus** [stashapp/CommunityScripts#425]
Starting with version 5.0.0 released last week,  the watchdog library enforces  passing keywords with keyword arguments:
https://github.com/gorakhargosh/watchdog/blob/master/changelog.rst#500

Now when the script is run with latest requirements an error is thrown by this line:
`eventHandler = PatternMatchingEventHandler(patterns, None, False, True)`

This could be fixed either by adding the appropriate keywords to each call to watchdog methods, or by pinning watchdog<5 (which worked for me). In any case, it would be good to pin the dependencies to known working versions to prevent it from breaking again in the future.

**Comment by DogmaDragon** [comment]
@David-Maisonave

**Comment by DogmaDragon** [comment]
@DuctTape42

**Comment by David-Maisonave** [comment]
FYI:
Plugin FileMonitor is working with the new watchdog version, and (IMHO) it's easier to use and has more features than [stash-watcher].
