### ISSUE TITLE
TimeStampTrade broken since I updated to v0.27.X

### ISSUE THREAD

**Issue by johnhargreaves** [stashapp/CommunityScripts#456]
Greetings:

Once I updated to 0.27 (and wasn't fixed with .1 or ,2), I cannot get timeStampTrade to work.  At first, it was the syntax error ([#447 ](https://github.com/stashapp/CommunityScripts/issues/447).  But once I fixed that manually (per the suggestion in #448), I get a 422 error.

here is the log: I suspect something in the first event (GRAPHQL_VALIDATION_FAILED: Cannot spread fragment "Group" within itself via "GroupDescription".) that cascades but have not been able to drill down.  To be fair, my python skills are rudimentary at best (although I did replace the double quotes with single quotes ... :-)

Here is the log:
```log
2024-11-02 14:39:58
Error   
Plugin returned error: exit status 1
2024-11-02 14:39:58
Error   
[Plugin / Timestamp Trade] Exception: 422 Unprocessable Entity query failed. v0.27.2-76648
2024-11-02 14:39:58
Error   
[Plugin / Timestamp Trade]     raise Exception(error_msg)
2024-11-02 14:39:58
Error   
[Plugin / Timestamp Trade]   File "C:\python311\Lib\site-packages\stashapi\classes.py", line 270, in _handle_GQL_response
2024-11-02 14:39:58
Error   
[Plugin / Timestamp Trade]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-02 14:39:58
Error   
[Plugin / Timestamp Trade]     return self._handle_GQL_response(response)
2024-11-02 14:39:58
Error   
[Plugin / Timestamp Trade]   File "C:\python311\Lib\site-packages\stashapi\classes.py", line 227, in _GQL
2024-11-02 14:39:58
Error   
[Plugin / Timestamp Trade]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-02 14:39:58
Error   
[Plugin / Timestamp Trade]     return self._GQL(query, variables)
2024-11-02 14:39:58
Error   
[Plugin / Timestamp Trade]   File "C:\python311\Lib\site-packages\stashapi\stashapp.py", line 216, in call_GQL
2024-11-02 14:39:58
Error   
[Plugin / Timestamp Trade]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-02 14:39:58
Error   
[Plugin / Timestamp Trade]     result = self.call_GQL(query, variables)
2024-11-02 14:39:58
Error   
[Plugin / Timestamp Trade]   File "C:\python311\Lib\site-packages\stashapi\stashapp.py", line 1484, in find_scene
2024-11-02 14:39:58
Error   
[Plugin / Timestamp Trade]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-02 14:39:58
Error   
[Plugin / Timestamp Trade]     scene = stash.find_scene(json_input["args"]["scene_id"])
2024-11-02 14:39:58
Error   
[Plugin / Timestamp Trade]   File "E:\plugins\community\timestampTrade/timestampTrade.py", line 1437, in <module>
2024-11-02 14:39:58
Error   
[Plugin / Timestamp Trade] Traceback (most recent call last):
2024-11-02 14:39:58
Error   
[Plugin / Timestamp Trade] 422 Unprocessable Entity query failed. v0.27.2-76648
2024-11-02 14:39:58
Error   
[Plugin / Timestamp Trade] 422 Unprocessable Entity GQL data response is null
2024-11-02 14:39:58
Error   
[Plugin / Timestamp Trade] GRAPHQL_VALIDATION_FAILED: Cannot spread fragment "Group" within itself via "GroupDescription".
```

And if it is a user-generated bug, I am happy to learn and be taught!

Thanks much,

**Comment by stg-annon** [comment]
this requires you to update `stashapp-tools` Groups are a new feature with the new Stash update and need to be handled differently

**Comment by magicswarmingswarm** [comment]
I have this issue in 0.26. I don't believe this is to do with 0.27 specifically, it was working fine before. Also updating stashapp-tools does not fix it. 
Error
Plugin returned error: exit status 1
[Plugin / Timestamp Trade]     KeyError: 'urls'
[Plugin / Timestamp Trade]     ~~~~^^^^^^^^
[Plugin / Timestamp Trade]     if not movie_scrape["urls"]:
[Plugin / Timestamp Trade]     File "C:\Users\x\Desktop\Stash\plugins\community\timestampTrade/timestampTrade.py", line 259, in processSceneTimestamTrade
[Plugin / Timestamp Trade]     processSceneTimestamTrade(s)
[Plugin / Timestamp Trade]     File "C:\Users\x\Desktop\Stash\plugins\community\timestampTrade/timestampTrade.py", line 24, in processScene
[Plugin / Timestamp Trade]     processScene(scene)
[Plugin / Timestamp Trade]     File "C:\Users\x\Desktop\Stash\plugins\community\timestampTrade/timestampTrade.py", line 1438, in <module>
[Plugin / Timestamp Trade]     Traceback (most recent call last):

**Comment by stg-annon** [comment]
@magicswarmingswarm that is a different error

`Cannot spread fragment "Group" within itself via "GroupDescription"` has to do with 0.27 and how stashapp-tools automatically queries data

`KeyError: 'urls'` has to do with querying the `urls` field of movies and it not existing which would need some error handling

@johnhargreaves not sure what's going on with that new error seems like somethings missing from the error log

**Comment by johnhargreaves** [comment]
This is what I have when I initiated the "sync" action:

2024-11-07 09:36:02
Error   
Plugin returned error: exit status 1
2024-11-07 09:36:02
Error   
[Plugin / Timestamp Trade] KeyError: 'addTsTradeTag'
2024-11-07 09:36:02
Error   
[Plugin / Timestamp Trade]        ~~~~~~~~^^^^^^^^^^^^^^^^^
2024-11-07 09:36:02
Error   
[Plugin / Timestamp Trade]     if settings["addTsTradeTag"]:
2024-11-07 09:36:02
Error   
[Plugin / Timestamp Trade]   File "E:\plugins\community\timestampTrade/timestampTrade.py", line 60, in processSceneTimestamTrade
2024-11-07 09:36:02
Error   
[Plugin / Timestamp Trade]     ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
2024-11-07 09:36:02
Error   
[Plugin / Timestamp Trade]     processSceneTimestamTrade(s)
2024-11-07 09:36:02
Error   
[Plugin / Timestamp Trade]   File "E:\plugins\community\timestampTrade/timestampTrade.py", line 24, in processScene
2024-11-07 09:36:02
Error   
[Plugin / Timestamp Trade]     ~~~~~~~~~~~~^^^
2024-11-07 09:36:02
Error   
[Plugin / Timestamp Trade]     processScene(s)
2024-11-07 09:36:02
Error   
[Plugin / Timestamp Trade]   File "E:\plugins\community\timestampTrade/timestampTrade.py", line 486, in processAll
2024-11-07 09:36:02
Error   
[Plugin / Timestamp Trade]     ~~~~~~~~~~^^^^^^^
2024-11-07 09:36:02
Error   
[Plugin / Timestamp Trade]     processAll(query)
2024-11-07 09:36:02
Error   
[Plugin / Timestamp Trade]   File "E:\plugins\community\timestampTrade/timestampTrade.py", line 1454, in <module>
2024-11-07 09:36:02
Error   
[Plugin / Timestamp Trade] Traceback (most recent call last):
2024-11-07 09:36:01
Info    
[Plugin / Timestamp Trade] fetching data: 0 - 100 0.0%
2024-11-07 09:36:01
Info    
[Plugin / Timestamp Trade] 1 scenes to process.
2024-11-07 09:36:01
Info    
[Plugin / Timestamp Trade] Getting scene count

**Comment by PineappleTwilight** [comment]
I fixed this problem by opening the YAML file, copying the setting string associated with addTsTradeTag (described as adding the [Timestamp] tag to markers), and replacing that errored string with it. I then enabled the option in Stash and it works perfectly.

I am unsure which of these two fixes the problem, but feel free to try both!

**Comment by Raptor05** [comment]
> I fixed this problem by opening the YAML file, copying the setting string associated with addTsTradeTag (described as adding the [Timestamp] tag to markers), and replacing that errored string with it in the python file. I then enabled the option in Stash and it works perfectly.
> 
> I am unsure which of these two fixes the problem, but feel free to try both!

Could you describe a little bit deeper, what you have done? I have exactly the same issue.

**Comment by feederbox826** [comment]
closed by https://github.com/stashapp/CommunityScripts/commit/3e4fb6383e8a405ad5ed2b1d47502c75bd8d42de and https://github.com/stashapp/CommunityScripts/commit/ad21862c29f10bf185fd675ed0c4df5a59ad17ce
