### ISSUE TITLE
[Stash-AI] can't use in 27.2

### ISSUE THREAD

**Issue by KKKKeybird** [stashapp/CommunityScripts#464]
Log:
Something went wrong. It's likely a server issue, Please try again later.
Error: Cannot read properties of undefined (reading 'data')

**Comment by feederbox826** [comment]
The server has not been updated and is no longer maintained

**Comment by sdfsdffjisod** [comment]
It seems the server works fine (https://cc1234-stashtag.hf.space/), but API has changed (e.g. the endpoint seems to have changed  from https://cc1234-stashtag.hf.space/api/predict to https://cc1234-stashtag.hf.space/gradio_api/call/predict). Maybe the js can be updated with all the api changes?

**Comment by stg-annon** [comment]
from discord the original dev was able to get it working again but it is currently unmaintained
> I got visage's API working again by downgrading it to gradio 3.x but i'm not sure how long that will last on huggingface.
I'm willing to hand over / help transition to what ever the community wants to do next so if there is something I can do to aid that let me know.
> \- cc1234
