### ISSUE TITLE
[markerTagToScene] Add all tags of Scene Marker to the Scene

### ISSUE THREAD

**Issue by IAmKontrast** [stashapp/CommunityScripts#48]
markerTagToScene v1.0 adds the primary tag of Scene Marker to the Scene on marker create/update.
I would like to have the option to activate 'all tags'.

**Comment by scruffynerf** [comment]
Looks like we have 3 different approaches to solve this and hopefully we'll get one in place soon.
I've asked @stg-annon to review his version of this as well.

**Comment by feederbox826** [comment]
closed by #311
