### ISSUE TITLE
[renamer] Fix $studio_family tag

### ISSUE THREAD

**Issue by sashizu** [stashapp/CommunityScripts#49]
When using the $studio_family tag, "_family" is appended to the studio name instead of using data from $studio or $parent_studio.

renamerOnUpdate does not have the issue.

Recommend changing the order of the template fields to process $studio_family before $studio

Current:

TEMPLATE_FIELD = "$date $year $performer $title $height $resolution $studio $parent_studio $studio_family $video_codec $audio_codec".split(" ")

Recommendation: ( from renamerOnUpdate )

TEMPLATE_FIELD = "$date $year $performer $title $height $resolution $parent_studio $studio_family $studio $rating $tags $video_codec $audio_codec".split(" ")

Normally, I would do a pull request and submit the change - however, I am remote and an issue is easier.

Thanks,

Sashizu

**Comment by bnkai** [comment]
renamer is no longer maintained.
renamerOnUpdate now includes all functionality and is to be used instead
