### ISSUE TITLE
 [renamerOnUpdate] Performer Count Includes Males When Male Performers are Disabled

### ISSUE THREAD

**Issue by user78476** [stashapp/CommunityScripts#50]
Not sure if this is a bug or an enhancement, but I noticed that when you set the performer limit at a specific number (say 3), but you also set it to ignore male performers, it still drops the performers if there are a total of 3 or more performers.

Wondering if the logic could be changed to check whether to include male performers and if not, then only count female. 

As an example, it would be nice to have the name include Riley Reed even though there are more than 4 performers in this scene: https://www.blackedraw.com/videos/girlfriend-gangbang-at-the-after-party

**Comment by Belleyy** [comment]
Yea it's a problem with the logic I use. It check the number of performer then check more in details.
Will fix it.
