### ISSUE TITLE
Latest renamerOnUpdate

### ISSUE THREAD

**Issue by PsychoSid** [stashapp/CommunityScripts#52]
Hello,

Just updated all my pip stuff this morning and now getting the following message from the plugin.

```
ERRO[2022-06-27 12:05:05] [Plugin / renamerOnUpdate] /usr/local/lib/python3.10/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.1.0) doesn't match a supported version!
ERRO[2022-06-27 12:05:05] [Plugin / renamerOnUpdate]   warnings.warn(
```

I don't like to downgrade/pin versions if I can get away with it.

Cheers.

**Comment by Belleyy** [comment]
What version of Request module you have ?

**Comment by PsychoSid** [comment]
Thanks. It was the `chardet` that was updated to v5.0.0 from my pip update logs. Moving back to v4.0.0 solved it for now. But as that has hit the repos it might become a wider issue for people.

**Comment by bnkai** [comment]
Closing as issue was resolved
