### ISSUE TITLE
[Sqlite_Renamer] [Feature Request] Catch all filename template after edits based on tags_dict

### ISSUE THREAD

**Issue by JediMaster25** [stashapp/CommunityScripts#58]
After it modifies all the scenes for each of the tags in `tags_dict` it should give the option to provide a `filename_template` for the rest of the scenes not yet modified. To do this subtract the list of scenes containing each of the tags from the list of all scenes. Apply the catch all filename_template to the resulting list of scenes.

**Comment by bnkai** [comment]
Sqlite renamer is no more developed/maintained. if you want to request some more functionality check first renamerOnupdate and then open a new issue for that plugin
