### ISSUE TITLE
[renamerOnUpdate] Advanced filename formatting

### ISSUE THREAD

**Issue by coscosname** [stashapp/CommunityScripts#68]
Please add more formatting options like [Advanced formatting in Calibre - Conditionally including text](https://manual.calibre-ebook.com/template_lang.html#advanced-formatting)

Example:
I want to use the `"[$studio] $date - $title"`  template but the scene doesn't have a date specified so I get `[studio] - title.mp4` file name

I would rather get the name `[studio] title.mp4`

**Comment by bnkai** [comment]
Closing as completed
