### ISSUE TITLE
renamerOnUpdate doesn't work with Files refractor release

### ISSUE THREAD

**Issue by ferengi82** [stashapp/CommunityScripts#73]
hi,
im testing the new files refractor release (https://github.com/stashapp/stash/releases/tag/files-refactor-release)
renamerOnUpdate throws many errors and doesn't work anymore, maybe someone can look into it?

`22-08-22 21:54:37
Error   
Scene.Update.Post [renamerOnUpdate]: returned error: exit status 1
2022-08-22 21:54:37
Error   
[Plugin / renamerOnUpdate]     cursor.execute("SELECT id FROM scenes WHERE path LIKE ? AND NOT id=?;", ["%" + folder_name + "_" + new_filename, FRAGMENT_SCENE_ID])
2022-08-22 21:54:37
Error   
[Plugin / renamerOnUpdate]   File "/root/stash-sortieren/plugins/renamerOnUpdate/renamerOnUpdate.py", line 512, in <module>
2022-08-22 21:54:37
Error   
[Plugin / renamerOnUpdate] Traceback (most recent call last):
2022-08-22 21:54:37
Error   
[Plugin / renamerOnUpdate] sqlite3.OperationalError: no such column: path
2022-08-22 21:54:37
Debug   
[Plugin / renamerOnUpdate] Python successfully connected to SQLite
2022-08-22 21:54:37
Debug   
[Plugin / renamerOnUpdate] [NEW] Filename: /storage/xxx/000-studio/MagmaFilm/MagmaFilm - 2002-09-15 - Hotel Fickmichgut - Scene 1 - Sibel Kekilli.avi
2022-08-22 21:54:37
Debug   
[Plugin / renamerOnUpdate] [OLD] Filename: /storage/xxx/Darsteller-umwandeln/Sibel_Kekilli/03_Hotel Fickmichgut - Scene 1.avi`

**Comment by Tscherno** [comment]
- You can have multiple file for the same scene. Should the plugin rename every file related to this scene ?
I would opt for that. Try to rename all of them.

- The mover part will only work to scene that only have 1 file associated to it, because which file to move ?
Try to move them all. If someone really wants to have multiple versions, he should include some unique identifier in the pattern (i guess quality).

**Comment by Tscherno** [comment]
No it's time for an update - the refactored stash version is on :develop

**Comment by AnonTester** [comment]
Multiple files of the same scene or at least with the same name was possible before as well when manually assigning a file to an existing scene. The renamerOnUpdate addon would fail to rename as a file with the same name in the same folder already existed.
I made some adjustments and was planning to do a PR, but as the database structure of stash changed and this addon doesn't work any longer, I'll have to wait and/or hope you'll add this functionality as it is rather relevant with the new stash app change.

What I did was to check if the file already exists and then repeat the new filename creation in a loop, add ".1", ".2", etc to the filename and keep checking until a valid filename is available.
code example (I'm sure that could be improved):
```
# Looking for duplicate path
cursor.execute("SELECT id FROM scenes WHERE path LIKE ? AND NOT id=?;", ["%" + current_directory + "_" + new_filename, FRAGMENT_SCENE_ID])
dupl_check = cursor.fetchall()
if len(dupl_check) > 0:
    for dupl_row in dupl_check:
        log.LogError("Identical path: [{}]".format(dupl_row[0]))
    exit_plugin(err="Duplicate path detected, check log!")
# Looking for duplicate filename, add number to filename if duplicate found
dupcounter=1
while True:
    cursor.execute("SELECT id FROM scenes WHERE path LIKE ? AND NOT id=?;", ["%" + new_filename, FRAGMENT_SCENE_ID])
    dupl_check = cursor.fetchall()
    if len(dupl_check) > 0:
        for dupl_row in dupl_check:
            log.LogWarning("Duplicate filename: [{}]".format(dupl_row[0]))
            dupcounter = dupcounter + 1
            new_filename = makeFilename(scene_information, filename_template) + "." + str(dupcounter) + file_extension
            # Replace the old filename by the new in the filepath
            #log.LogWarning("Old path {}".format(current_path))
            dir_name = os.path.dirname(current_path)
            join_path = os.path.join(dir_name, new_filename)
            #log.LogWarning("Join path {}".format(join_path))
            new_path = os.path.realpath(join_path)
            #log.LogWarning("New path {}".format(new_path))
    else:
        break
```

Also, I think it would be better if all files related to renamerOnUpdate had the same name to avoid any possible conflicts with other plugins as all plugins are in the same directory.
Suggestion:
renamerOnUpdate.config
renamerOnUpdate.log
renamerOnUpdate_log.py
renamerOnUpdate.py
renamerOnUpdate.yml

Thanks for this plugin and I'm looking forward to testing your recent update once it's compatible with the new stash database structure.
