### ISSUE TITLE
[Sqlite_Renamer] sqlite3.OperationalError: no such column: path

### ISSUE THREAD

**Issue by RileyMo5038** [stashapp/CommunityScripts#76]
The script fails on my Line 137
        _query = "SELECT id,path,title,date,studio_id,height from scenes {};".format(optionnal_query)_

When viewed in DB Browser, there does not seem to be a column named 'path' in the 'scenes' table.

Possibly this now out of date through updates?

**Comment by sashizu** [comment]
This is definitely a stop-gap fix and use at your own risk!

I backed up several files and re-organized them to get the plugin to fire and update the filename. It appears to work, however, I agree that migrating from direct sqlite db calls to GraphQL is the best way forward.

The path column in the scenes table is now the basename column in the files table.

In checking_duplicate_db replace the following  (should be three select statements):

SELECT id FROM scenes WHERE path
with
SELECT id FROM files WHERE basename

In db_rename replace the following:

UPDATE scenes SET path=?
with
UPDATE files SET basename=?

As I mentioned at the top, this is stop-gap fix that I am still testing: DB cleanup, etc. 

However, it does appear to work until the plugin can by re-worked by someone more knowledgeable.

**Comment by bnkai** [comment]
sqlite renamer is no longer maintained.
renamerOnUpdate now includes all functionality and is to be used instead
