### ISSUE TITLE
[renamerOnUpdate] renamed files differ from configured template

### ISSUE THREAD

**Issue by ArcCdr** [stashapp/CommunityScripts#79]
Hi @Belleyy,

First, let me congratulate you for the very polished and feature rich plugin!

I use the following default_template config: `$studio -=- $date -=- $performer -=- $title`

The renamed file are actually `studio =- date =- performer =- title.mp4` (missing the first dash in my separator). Probably a regex trick somewhere in the code...

I guess I use an uncommon separator, but I would really appreciate if you can fix it when you have the time.

Thanks!

**Comment by bnkai** [comment]
Fixed by #107
Closing
