### ISSUE TITLE
[renamerOnUpdate] More nuance in date-related elements?

### ISSUE THREAD

**Issue by BrekiTomasson** [stashapp/CommunityScripts#84]
I find `$date` and `$year` to be somewhat unflexible. Wouldn't it be better to have something like `$yyyy`, `$yy`, `$mm` and `$dd` instead? That way, one could make templates like `$studio.$yy.$mm.$dd.$performer.$title`, for example.

**Comment by DogmaDragon** [comment]
https://github.com/stashapp/CommunityScripts/pull/80 adds $date_format

**Comment by bnkai** [comment]
#80 with $date_format support was merged. Closing this as the date options supoported now (<https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes>) are quite flexible
