### ISSUE TITLE
[renamerOnUpdate] Don't work with Stash 0.17.1 anymore

### ISSUE THREAD

**Issue by Zheltyy** [stashapp/CommunityScripts#87]
Getting the following errors in the Stash Log while trying to update a title:

2022-10-21 07:57:52 Info [Plugin / renamerOnUpdate] The filename will be changed
2022-10-21 07:57:52 Error [Plugin / renamerOnUpdate] Error during database operation (no such column: path)

renamerOnUpdate is on the newest version that is available

**Comment by Tscherno** [comment]
Use the one from this pull request, it's not merged yet:
https://github.com/stashapp/CommunityScripts/pull/80

**Comment by bnkai** [comment]
#80 with file refactor support was merged. Closing this

**Comment by MRobi1** [comment]
Having issues with the merged pull request.

```
2022-10-25 10:30:56
Error   
Scene.Update.Post [renamerOnUpdate]: returned error: exit status 1
2022-10-25 10:30:56
Error   
[Plugin / renamerOnUpdate]     cursor.execute("SELECT id FROM scenes WHERE path LIKE ? AND NOT id=?;", ["%" + folder_name + "_" + new_filename, FRAGMENT_SCENE_ID])
2022-10-25 10:30:56
Error   
[Plugin / renamerOnUpdate] sqlite3.OperationalError: no such column: path
2022-10-25 10:30:56
Error   
[Plugin / renamerOnUpdate] Traceback (most recent call last):
2022-10-25 10:30:56
Error   
[Plugin / renamerOnUpdate]   File "/root/.stash/plugins/renamerOnUpdate/renamerOnUpdate.py", line 427, in <module>
```

line 427 appears to reference p_non_organized. I've tried various combinations of leaving blank "", different paths as well as r"^*\$performer". Continue to receive the same error regardless.
