### ISSUE TITLE
[renamerOnUpdate] Studio Rename Not Working Properly

### ISSUE THREAD

**Issue by user78476** [stashapp/CommunityScripts#93]
Not sure what I'm doing wrong, but I just updated to the most recent version and now my studio rename configuration is no longer working. 

Here's my config:
```
####################################################################
#           TEMPLATE FILENAME (Rename your files)

# Priority : Tags > Studios > Default

# Templates to use for given tags
# Add or remove as needed or leave it empty/comment out
# you can specific group with {}. exemple: [$studio] {$date -} $title, the '-' will be removed if no date
tag_templates = {
    "renameMovie": "$title ($year) [$height]",
}

# Adjust the below if you want to use studio names instead of tags for the renaming templates
studio_templates = {
        "Tonight's Girlfriend": "tonightsgirlfriend - $date - $performer [$height]",
        "Tushy": "$studio - $date - $performer [$height]",
        "Vixen": "$studio - $date - $performer [$height]",
}

# Change to True to use the default template if no specific tag/studio is found
use_default_template = True
# Default template, adjust as needed
default_template = "$performer - $date - $title [$studio][$height]"
```
I have a file from Tonight's Girlfriend which is tagged with the studio, but it's renaming based on the default template instead.

Expected Filename Created: `tonightsgirlfriend - 2022-10-28 - lauren phillips [1080p].mp4`
Actual Filename Created: `lauren phillips - 2022-10-28 - busty redhead lauren phillips rides her fans big cock [tonightsgirlfriend][1080p].mp4`

Is there any way to tell why it's not picking up the studio properly? I've removed it and added it back in and still no luck. This is the exact config that was working until the update.

**Comment by hphpanon** [comment]
@user78476 It looks like there was a bug where the filename handling was attempting to use the `p_studio_templates` config value to determine whether it should attempt to do any changes. The change in #94 _should_ fix it if you want to try it out locally.

**Comment by user78476** [comment]
Just made the change locally and it's now working correctly based on testing ~20 files.
